pipelines:
  branches:
    master:
      - step:
          name: Deploy to production server
          deployment: production
          trigger: manual
          image: php:7.1.5-alpine
          script:
            - apk update --no-cache && apk add --no-cache openssh-client
            - curl -L https://deployer.org/releases/v$DEPLOYER_VERSION/deployer.phar > /usr/local/bin/dep && chmod +x /usr/local/bin/dep
            - dep deploy